language: node_js
node_js:
  - "15"
dist: trusty
sudo: required
branches:
  only:
    - main
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://github.com/amine187/pico-pixel-challenge
